// GSD Extension — Preference & Observer Type Definitions
// Type surface for preference promotion (pattern-preferences.ts) and
// observer analysis (observer.ts). Consumed by both modules, their tests,
// and downstream S03 recall injection.

import type { DiagnosisCategory, CorrectionScope } from "./correction-types.ts";

// ─── Preference Types ──────────────────────────────────────────────────────

/**
 * A promoted preference entry persisted in preferences.jsonl.
 * Created when ≥3 corrections share the same category+scope.
 */
export interface PreferenceEntry {
  /** Diagnosis category from the 14-category taxonomy */
  category: DiagnosisCategory;
  /** Correction scope the preference applies to */
  scope: CorrectionScope;
  /** Human-readable preference text describing the learned pattern */
  preference_text: string;
  /** Confidence score: count/(count+2), range (0, 1) */
  confidence: number;
  /** Number of corrections that contributed to this preference */
  source_count: number;
  /** ISO timestamp of the most recent correction that fed this preference */
  last_correction_ts: string;
  /** ISO timestamp when this preference was first created */
  created_at: string;
  /** ISO timestamp when this preference was last updated */
  updated_at: string;
  /** ISO timestamp when retired, or null if active */
  retired_at: string | null;
  /** Identifier of who/what retired this preference, or null if active */
  retired_by: string | null;
}

// ─── Promotion Result Types ────────────────────────────────────────────────

/**
 * Structured result from checkAndPromote().
 * Always returns — never throws.
 */
export interface PromoteResult {
  /** Whether a preference was promoted (created or updated) */
  promoted: boolean;
  /** Reason for non-promotion */
  reason?: "invalid_entry" | "below_threshold" | "error";
  /** Number of matching corrections found */
  count?: number;
  /** Computed confidence score when promoted */
  confidence?: number;
}

/**
 * Structured result from writePreference().
 * Always returns — never throws.
 */
export interface WritePreferenceResult {
  /** Whether the preference was written successfully */
  written: boolean;
  /** Reason for write failure */
  reason?: "error";
}

// ─── Observer / Suggestion Types ───────────────────────────────────────────

/**
 * A suggestion generated by analyzePatterns() — represents an actionable
 * insight derived from aggregated correction patterns.
 */
export interface SuggestionEntry {
  /** Unique identifier for this suggestion */
  id: string;
  /** Type of suggestion */
  type: "refine_skill" | "new_skill_needed";
  /** Name of the target skill, or null if no skill mapping exists */
  target_skill: string | null;
  /** Diagnosis category that triggered this suggestion */
  category: DiagnosisCategory;
  /** Human-readable summary of the scopes involved */
  scope_summary: string;
  /** Number of corrections that contributed to this suggestion */
  correction_count: number;
  /** Sample correction texts for context */
  sample_corrections: string[];
  /** Current lifecycle status */
  status: "pending" | "accepted" | "dismissed" | "refined";
  /** ISO timestamp when the suggestion was created */
  created_at: string;
  /** ISO timestamp when accepted, or null */
  accepted_at: string | null;
  /** ISO timestamp when dismissed, or null */
  dismissed_at: string | null;
  /** Reason for dismissal, or null */
  dismiss_reason: string | null;
  /** ISO timestamp when refined, or null */
  refined_at: string | null;
}

/**
 * A suggestion that was skipped due to a guardrail (cooldown, duplicate, etc).
 * Recorded in suggestions.json metadata for diagnostics.
 */
export interface SkippedSuggestion {
  /** Diagnosis category of the skipped suggestion */
  category: DiagnosisCategory;
  /** Target skill that was blocked, or null */
  target_skill: string | null;
  /** Why the suggestion was skipped */
  reason: string;
  /** ISO timestamp when the skip occurred */
  skipped_at: string;
  /** ISO timestamp when the cooldown expires, if applicable */
  cooldown_expires?: string;
}

/**
 * The full suggestions.json document structure.
 * Includes metadata for watermark tracking, versioning, and skip diagnostics.
 */
export interface SuggestionsDocument {
  metadata: {
    /** ISO timestamp of the last analyzePatterns() run, or null if never run */
    last_analyzed_at: string | null;
    /** Schema version for forward compatibility */
    version: number;
    /** Suggestions that were blocked by guardrails */
    skipped_suggestions: SkippedSuggestion[];
  };
  /** Active suggestion entries */
  suggestions: SuggestionEntry[];
}

// ─── Analyze Result ────────────────────────────────────────────────────────

/**
 * Structured result from analyzePatterns().
 * Always returns — never throws.
 */
export interface AnalyzeResult {
  /** Whether analysis completed successfully */
  analyzed: boolean;
  /** Number of new suggestions written */
  suggestions_written?: number;
  /** Reason for analysis failure */
  reason?: "error";
}
